services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ntfy-reminders-server
    restart: unless-stopped
    environment:
      - TZ=${CRON_TZ}
      - NTFY_TOKEN=${NTFY_TOKEN}
      - NTFY_HOST=${NTFY_HOST}
      - NTFY_TOPIC=${NTFY_TOPIC}
      - MONGO_URI=${MONGO_URI}
      - CRON_TZ=${CRON_TZ}

  portal:
    build:
      context: ./portal
      dockerfile: Dockerfile
    container_name: ntfy-reminders-portal
    restart: unless-stopped
    ports:
      - "47521:47521"
    environment:
      - NODE_ENV=production
